global:
  imagePullSecrets: []  # Keep empty
  # imagePullSecrets:
  #   - name: cr-maksit-pull

components:
  server:
    image:
      registry: cr.maks-it.com
      repository: certs-ui/server
      pullPolicy: Always
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Production
      - name: ASPNETCORE_HTTP_PORTS
        value: "5000"
    service:
      enabled: true
      type: ClusterIP
      port: 5000
      targetPort: 5000
    persistence:
      storageClass: local-path
      volumes:
        - name: acme
          mountPath: /acme
          type: pvc
          pvc:
            create: true
            size: 50Mi
            accessModes: [ReadWriteOnce]
        - name: cache
          mountPath: /cache
          type: pvc
          pvc:
            create: true
            size: 50Mi
            accessModes: [ReadWriteOnce]
        - name: data
          mountPath: /data
          type: pvc
          pvc:
            create: true
            size: 50Mi
            accessModes: [ReadWriteOnce]
    secretsFile:
      key: appsecrets.json
      mountPath: /secrets/appsecrets.json
      content: |
        {
          "Auth": {
            "Secret": "",
            "Pepper": ""
          },
          "Agent": {
            "AgentKey": ""
          },
        }
      keep: true

    configMapFile:
      key: appsettings.json
      mountPath: /configMap/appsettings.json
      content: |
        {
          "Logging": {
            "LogLevel": {
              "Default": "Information",
              "Microsoft.AspNetCore": "Warning"
            }
          },
          "Configuration": {
            "Auth": {
              "Issuer": "",
              "Audience": "",
              "Expiration": 15, // Access token lifetime in minutes (default: 15 minutes)
              "RefreshExpiration": 180, // Refresh token lifetime in days (default: 180 days)
            },

            "Agent": {
              "AgentHostname": "http://websrv0001.corp.maks-it.com",
              "AgentPort": 5000,
              "ServiceToReload": "haproxy"
            },

            "Production": "https://acme-v02.api.letsencrypt.org/directory",
            "Staging": "https://acme-staging-v02.api.letsencrypt.org/directory",
            "CacheFolder": "/cache",
            "AcmeFolder": "/acme",

            "DataFolder": "/data",
            "SettingsFile": "/data/settings.json",
          }
        }
      keep: true

  client:
    image:
      registry: cr.maks-it.com
      repository: certs-ui/client
      pullPolicy: Always
    service:
      enabled: true
      type: ClusterIP
      port: 5173
      targetPort: 5173
    configMapFile:
      key: config.js
      mountPath: /app/dist/config.js
      content: |
        window.RUNTIME_CONFIG = {
          API_URL: "http://<your-server-hostname>/api"
        };
      keep: true

  reverseproxy:
    image:
      registry: cr.maks-it.com
      repository: certs-ui/reverseproxy
      pullPolicy: Always
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Production
      - name: ASPNETCORE_HTTP_PORTS
        value: "8080"
    service:
      enabled: true
      type: ClusterIP
      port: 8080
      targetPort: 8080
      # type: LoadBalancer
      # port: 8080
      # targetPort: 8080
      # loadBalancerIP: "172.16.0.5"
      # annotations:
      #   lbipam.cilium.io/ips: "172.16.0.5" 
      # labels:
      #   export: "bgp"
      # externalTrafficPolicy: Local
      # sessionAffinity: ClientIP
      # sessionAffinityConfig:
      #   clientIP:
      #     timeoutSeconds: 10800