"use client" // Add this line

import React, { FC, useState, useEffect, useRef } from 'react'
import './globals.css'
import { SideMenu } from '@/components/sidemenu'
import { TopMenu } from '@/components/topmenu'
import { Footer } from '@/components/footer'
import { OffCanvas } from '@/components/offcanvas'
import { Loader } from '@/components/loader' // Import the Loader component
import { Metadata } from 'next'
import { Toast } from '@/components/toast'
import { Provider } from 'react-redux'
import { store }  from '@/redux/store'

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const Layout: FC<{ children: React.ReactNode }> = ({ children }) => {
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false)
  const [isManuallyCollapsed, setManuallyCollapsed] = useState(false)
  //const [isLoading, setIsLoading] = useState(true) // State to control the loader visibility

  const init = useRef(false)

  const toggleSidebar = () => {
    setIsSidebarCollapsed((prev) => !prev)
  }

  const manuallyToggleSidebar = () => {
    setManuallyCollapsed((prev) => !prev)
    toggleSidebar()
  }

  const handleResize = () => {
    if (!isManuallyCollapsed) {
      if (window.innerWidth <= 768) {
        if (!isSidebarCollapsed) setIsSidebarCollapsed(true)
      } else {
        if (isSidebarCollapsed) setIsSidebarCollapsed(false)
      }
    } else {
      if (isManuallyCollapsed) return

      // Reset manualCollapse if the window is resized to a state that should automatically collapse/expand the sidebar
      if (window.innerWidth > 768 && isSidebarCollapsed) {
        setIsSidebarCollapsed(false)
      } else if (window.innerWidth <= 768 && !isSidebarCollapsed) {
        setIsSidebarCollapsed(true)
      }
    }
  }

  useEffect(() => {
    if (!init.current) {
      handleResize() // Set the initial state based on the current window width
      init.current = true
    }

    window.addEventListener('resize', handleResize)
    return () => {
      window.removeEventListener('resize', handleResize)
    }
  }, [isSidebarCollapsed, isManuallyCollapsed])

  const [isOffCanvasOpen, setIsOffCanvasOpen] = useState(false)

  const toggleOffCanvas = () => {
    setIsOffCanvasOpen((prev) => !prev)
  }

  return (
    <html lang="en">
      <body className="h-screen overflow-hidden">
        <Provider store={store}>
          <Loader />

          <div className="flex h-full">
            <SideMenu isCollapsed={isSidebarCollapsed} toggleSidebar={manuallyToggleSidebar} />
            <div className="flex flex-col flex-1">
              <TopMenu onToggleOffCanvas={toggleOffCanvas} />
              <main className="flex-1 p-4 transition-transform duration-300">
                {children}
              </main>
              <Footer />
            </div>
          </div>
          <OffCanvas isOpen={isOffCanvasOpen} onClose={toggleOffCanvas} />
          <Toast />
        </Provider>
      </body>
    </html>
  )
}

export default Layout
