'use client'

import React, { FC, useState, useEffect, useRef } from 'react'
import { SideMenu } from '@/components/sidemenu'
import { TopMenu } from '@/components/topmenu'
import { Footer } from '@/components/footer'
import { OffCanvas } from '@/components/offcanvas'
import { Loader } from '@/components/loader'
import { Metadata } from 'next'
import { Toast } from '@/components/toast'
import { Provider } from 'react-redux'
import { store } from '@/redux/store'
import './globals.css'

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const Layout: FC<{ children: React.ReactNode }> = ({ children }) => {
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false)
  const [isManuallyCollapsed, setManuallyCollapsed] = useState(false)

  const init = useRef(false)

  const toggleSidebar = () => {
    setIsSidebarCollapsed((prev) => !prev)
  }

  const manuallyToggleSidebar = () => {
    setManuallyCollapsed((prev) => !prev)
    toggleSidebar()
  }

  const handleResize = () => {
    if (!isManuallyCollapsed) {
      if (window.innerWidth <= 768) {
        if (!isSidebarCollapsed) setIsSidebarCollapsed(true)
      } else {
        if (isSidebarCollapsed) setIsSidebarCollapsed(false)
      }
    } else {
      if (isManuallyCollapsed) return

      if (window.innerWidth > 768 && isSidebarCollapsed) {
        setIsSidebarCollapsed(false)
      } else if (window.innerWidth <= 768 && !isSidebarCollapsed) {
        setIsSidebarCollapsed(true)
      }
    }
  }

  useEffect(() => {
    if (!init.current) {
      handleResize()
      init.current = true
    }

    window.addEventListener('resize', handleResize)
    return () => {
      window.removeEventListener('resize', handleResize)
    }
  }, [isSidebarCollapsed, isManuallyCollapsed])

  const [isOffCanvasOpen, setIsOffCanvasOpen] = useState(false)

  const toggleOffCanvas = () => {
    setIsOffCanvasOpen((prev) => !prev)
  }

  return (
    <html lang="en">
      <body className="h-screen overflow-hidden flex flex-col">
        <Provider store={store}>
          <Loader />

          <div className="flex flex-1 overflow-hidden">
            <SideMenu
              isCollapsed={isSidebarCollapsed}
              toggleSidebar={manuallyToggleSidebar}
            />

            <div className="flex flex-col flex-1 overflow-hidden">
              <TopMenu onToggleOffCanvas={toggleOffCanvas} />
              <main className="flex-1 p-4 overflow-y-auto">{children}</main>
              <Footer className="flex-shrink-0" />
            </div>
          </div>

          <OffCanvas isOpen={isOffCanvasOpen} onClose={toggleOffCanvas} />
          <Toast />
        </Provider>
      </body>
    </html>
  )
}

export default Layout
