"use client"; // Add this line

import React, { FC, useState } from 'react';
import './globals.css';
import { SideMenu } from '../components/sidemenu';
import { TopMenu } from '../components/topmenu';
import { Footer } from '../components/footer';
import { OffCanvas } from '../components/offcanvas';
import { Metadata } from 'next';

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: Readonly<{
  children: React.ReactNode;
}>) => {
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);
  const [isOffCanvasOpen, setIsOffCanvasOpen] = useState(false);

  const toggleSidebar = () => {
    setIsSidebarCollapsed(!isSidebarCollapsed);
  };

  const toggleOffCanvas = () => {
    setIsOffCanvasOpen(!isOffCanvasOpen);
  };

  return (
    <html lang="en">
      {/* <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head> */}
      <body className="h-screen overflow-hidden">
        <div className="flex h-full">
          <SideMenu isCollapsed={isSidebarCollapsed} toggleSidebar={toggleSidebar} />
          <div className="flex flex-col flex-1">
            <TopMenu onToggleOffCanvas={toggleOffCanvas} />
            <main className={`flex-1 p-4 transition-transform duration-300 ${isOffCanvasOpen ? 'transform translate-x-64' : ''}`}>
              {children}
            </main>
            <Footer />
          </div>
        </div>
        <OffCanvas isOpen={isOffCanvasOpen} onClose={toggleOffCanvas} />
      </body>
    </html>
  );
};

export default Layout;
