{{- $roll := ((.Values.rollme | default (now | unixEpoch)) | toString) -}}

{{- $root := . -}}
{{- range $compName, $comp := .Values.components }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "certs-ui.fullname" $root }}-{{ $compName }}
  labels:
    {{- include "certs-ui.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      app.kubernetes.io/name: {{ include "certs-ui.name" $root }}
      app.kubernetes.io/component: {{ $compName }}
  template:
    metadata:
      labels:
        {{- include "certs-ui.labels" $root | nindent 8 }}
        app.kubernetes.io/component: {{ $compName }}
      {{- if and $comp.secretsFile $comp.secretsFile.forceUpdate }}
      annotations:
        rollme: "{{$roll}}"
      {{- end }}
    spec:
      {{- include "certs-ui.imagePullSecrets" $root | nindent 6 }}
      containers:
        - name: {{ $compName }}
          image: "{{ $comp.image.registry }}/{{ $comp.image.repository }}:{{ $comp.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" $comp.image.pullPolicy }}
          {{ $svc := default dict $comp.service }}
          {{ $tgt := default 8080 $svc.targetPort }}
          ports:
            - name: http
              containerPort: {{ $tgt }}
          {{- if $comp.env }}
          env:
            - name: ROLLOUT_TOKEN
              value: "{{$roll}}"
            {{- range $comp.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          {{- if eq $compName "client" }}
            - name: VITE_API_URL
              value: >
                {{- if eq $root.Values.components.reverseproxy.service.type "LoadBalancer" -}}
                http://{{ $root.Values.components.reverseproxy.service.loadBalancerIP }}:{{ $root.Values.components.reverseproxy.service.port }}
                {{- else -}}
                http://{{ include "certs-ui.fullname" $root }}-reverseproxy:{{ $root.Values.components.reverseproxy.service.port }}
                {{- end }}
            {{- end }}
          {{- $p := default dict $comp.persistence -}}
          {{- $vols := default (list) $p.volumes -}}
          {{- $hasVols := gt (len $vols) 0 -}}
          {{- $hasSecret := (hasKey $comp "secretsFile") -}}
          {{- if or $hasVols $hasSecret $comp.configMapFile }}
          volumeMounts:
            {{- range $vol := $vols }}
            - name: {{ $compName }}-{{ $vol.name }}
              mountPath: {{ $vol.mountPath }}
            {{- end }}
            {{- if $comp.secretsFile }}
            - name: {{ $compName }}-secrets
              mountPath: {{ $comp.secretsFile.mountPath }}
              subPath: {{ base $comp.secretsFile.mountPath }}
            {{- end }}
            {{- if $comp.configMapFile }}
            - name: {{ $compName }}-configmap
              mountPath: {{ $comp.configMapFile.mountPath }}
              subPath: {{ base $comp.configMapFile.mountPath }}
            {{- end }}
          {{- end }}
      {{- if or $hasVols $hasSecret $comp.configMapFile }}
      volumes:
        {{- range $vol := $vols }}
        - name: {{ $compName }}-{{ $vol.name }}
          {{- if eq $vol.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ include "certs-ui.fullname" $root }}-{{ $compName }}-{{ $vol.name }}
          {{- else if eq $vol.type "emptyDir" }}
          emptyDir: {{ toYaml (default dict $vol.emptyDir) | nindent 12 }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- if $comp.secretsFile }}
        - name: {{ $compName }}-secrets
          secret:
            secretName: {{ include "certs-ui.fullname" $root }}-{{ $compName }}-secrets
            items:
              - key: {{ $comp.secretsFile.key }}
                path: {{ base $comp.secretsFile.mountPath }}
        {{- end }}
        {{- if $comp.configMapFile }}
        - name: {{ $compName }}-configmap
          configMap:
            name: {{ include "certs-ui.fullname" $root }}-{{ $compName }}-configmap
            items:
              - key: {{ $comp.configMapFile.key }}
                path: {{ base $comp.configMapFile.mountPath }}
        {{- end }}
      {{- end }}
{{- end }}
