version: '3.9'

services:
  letsencryptapp:
    image: ${DOCKER_REGISTRY-}letsencryptapp
    build:
      context: .
      dockerfile: ClientApp/Dockerfile

  reverseProxy:
    image: ${DOCKER_REGISTRY-}reverseproxy
    build:
      context: .
      dockerfile: ReverseProxy/Dockerfile

  letsencryptserver:
    image: ${DOCKER_REGISTRY-}letsencryptserver
    build:
      context: .
      dockerfile: LetsEncryptServer/Dockerfile
