version: '3.9'

services:
  reverseProxy:
    ports:
      - "8080:8080"
    depends_on:
      - letsencryptapp
      - letsencryptserver

  # letsencryptapp:
  #   ports:
  #   - "3000:3000"

  letsencryptserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
    volumes:
      - ./docker-compose/LetsEncryptServer/acme:/app/bin/Debug/net8.0/acme
      - ./docker-compose/LetsEncryptServer/cache:/app/bin/Debug/net8.0/cache
    ports:
      - "5000:5000"

